server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/taskflow_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  secret: MySuperSecretKeyForTaskFlowApplication123456789
  expiration: 3600000

aws:
  region: ap-south-1

  s3:
    bucket-name: taskflow-pro-profile-images
    access-key: AKIATWHY2XNZNPVBAIF3
    secret-key: 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

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
